version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - npm install --save express body-parser cookie-parser debug ejs morgan serve-favicon
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --save express body-parser cookie-parser debug ejs morgan serve-favicon   
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
